sudo: required
services: 
  - docker


before_install:
  - docker build -t nebbigit/docker-react -f Dockerfile.dev .


script:
  - docker run nebbigit/docker-react npm run test -- --coverage
  
